/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pos;

/**
 *
 * @author Bagus Wijaya
 */
public class UiKasir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UiKasir.class.getName());

    /**
     * Creates new form UiKasir
     */
    public UiKasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        txtCariBarang = new javax.swing.JLabel();
        cmbCariBarang = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JLabel();
        txtFieldJumlah = new javax.swing.JTextField();
        btnTambahKeranjang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnHapusBarang = new javax.swing.JButton();
        panelKananAtas = new javax.swing.JPanel();
        lblTotalHarga = new javax.swing.JLabel();
        lblNominalHarga = new javax.swing.JLabel();
        panelKananBawah = new javax.swing.JPanel();
        lblUangBayar = new javax.swing.JLabel();
        txtFieldUangBayar = new javax.swing.JTextField();
        lblUangKembalian = new javax.swing.JLabel();
        lblNominalKembalian = new javax.swing.JLabel();
        btnTransaksiSelesaiCetakStruk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaStruk = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1049, 663));
        setSize(new java.awt.Dimension(1049, 663));

        panelKiri.setBackground(new java.awt.Color(255, 255, 255));

        txtCariBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtCariBarang.setText("Cari/Pilih Barang:");

        cmbCariBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtJumlah.setForeground(new java.awt.Color(0, 0, 0));
        txtJumlah.setText("Jumlah (Qty):");

        txtFieldJumlah.setText("1");

        btnTambahKeranjang.setBackground(new java.awt.Color(51, 102, 255));
        btnTambahKeranjang.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahKeranjang.setText("Tambah ke Keranjang");

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Harga", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        btnHapusBarang.setBackground(new java.awt.Color(255, 51, 51));
        btnHapusBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnHapusBarang.setText("Hapus Barang dari Keranjang");

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelKiriLayout.createSequentialGroup()
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCariBarang, 0, 264, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahKeranjang))
                    .addGroup(panelKiriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHapusBarang)))
                .addContainerGap())
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariBarang)
                    .addComponent(cmbCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah)
                    .addComponent(txtFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahKeranjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusBarang)
                .addContainerGap())
        );

        panelKananAtas.setBackground(new java.awt.Color(204, 204, 204));

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalHarga.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalHarga.setText("TOTAL YANG HARUS DIBAYAR:");

        lblNominalHarga.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNominalHarga.setForeground(new java.awt.Color(0, 0, 0));
        lblNominalHarga.setText("Rp 0");

        javax.swing.GroupLayout panelKananAtasLayout = new javax.swing.GroupLayout(panelKananAtas);
        panelKananAtas.setLayout(panelKananAtasLayout);
        panelKananAtasLayout.setHorizontalGroup(
            panelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKananAtasLayout.createSequentialGroup()
                        .addComponent(lblTotalHarga)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNominalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelKananAtasLayout.setVerticalGroup(
            panelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNominalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelKananBawah.setBackground(new java.awt.Color(204, 204, 204));

        lblUangBayar.setForeground(new java.awt.Color(0, 0, 0));
        lblUangBayar.setText("Uang Tunai (Bayar):");

        txtFieldUangBayar.setText("0");

        lblUangKembalian.setForeground(new java.awt.Color(0, 0, 0));
        lblUangKembalian.setText("Uang Kembalian:");
        lblUangKembalian.setToolTipText("");

        lblNominalKembalian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNominalKembalian.setForeground(new java.awt.Color(0, 0, 0));
        lblNominalKembalian.setText("Rp 0");

        btnTransaksiSelesaiCetakStruk.setBackground(new java.awt.Color(0, 204, 51));
        btnTransaksiSelesaiCetakStruk.setForeground(new java.awt.Color(0, 0, 0));
        btnTransaksiSelesaiCetakStruk.setText("TRANSAKSI SELESAI & CETAK STRUK");

        txtAreaStruk.setEditable(false);
        txtAreaStruk.setColumns(20);
        txtAreaStruk.setRows(5);
        txtAreaStruk.setText("Nama Toko:\nDaftar Barang:\nTotal:\nUang Bayar:\nKembalian:");
        txtAreaStruk.setToolTipText("");
        jScrollPane2.setViewportView(txtAreaStruk);

        javax.swing.GroupLayout panelKananBawahLayout = new javax.swing.GroupLayout(panelKananBawah);
        panelKananBawah.setLayout(panelKananBawahLayout);
        panelKananBawahLayout.setHorizontalGroup(
            panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKananBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(btnTransaksiSelesaiCetakStruk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelKananBawahLayout.createSequentialGroup()
                        .addGroup(panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUangKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUangBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldUangBayar)
                            .addComponent(lblNominalKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelKananBawahLayout.setVerticalGroup(
            panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKananBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUangBayar)
                    .addComponent(txtFieldUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUangKembalian)
                    .addComponent(lblNominalKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaksiSelesaiCetakStruk)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKananBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKananAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKananBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UiKasir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnTambahKeranjang;
    private javax.swing.JButton btnTransaksiSelesaiCetakStruk;
    private javax.swing.JComboBox<String> cmbCariBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNominalHarga;
    private javax.swing.JLabel lblNominalKembalian;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblUangBayar;
    private javax.swing.JLabel lblUangKembalian;
    private javax.swing.JPanel panelKananAtas;
    private javax.swing.JPanel panelKananBawah;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextArea txtAreaStruk;
    private javax.swing.JLabel txtCariBarang;
    private javax.swing.JTextField txtFieldJumlah;
    private javax.swing.JTextField txtFieldUangBayar;
    private javax.swing.JLabel txtJumlah;
    // End of variables declaration//GEN-END:variables
}
